import { Image, Text, View, ScrollView } from 'react-native';
import { styles } from '../styles/cautionscreen-styles';
import { useNavigation } from '@react-navigation/native';

const CautionScreen = ({ route }) => {

    const navigation = useNavigation();

    const { name } = route.params;

    const text = {
        'CIBERATAQUE': 'Mantén la Calma: Es crucial mantener la calma y no entrar en pánico. La respuesta rápida y efectiva requiere un enfoque tranquilo y controlado.\nDesconecta de la Red:Desconecta inmediatamente el dispositivo afectado de la red, ya sea mediante la desconexión del cable de red o desactivando la conexión Wi-Fi. Esto ayuda a prevenir la propagación del ataque y limita el daño.\nReporta el Incidente: Informa del ciberataque a tu equipo de seguridad informática o al departamento de TI de tu organización. Cuanto antes sepan del incidente, más rápido podrán tomar medidas para contener y mitigar el daño.\nRecopila Información: Intenta recopilar información sobre el ataque, como mensajes de error, archivos afectados o cualquier actividad inusual. Esta información será valiosa para determinar la naturaleza del ataque y para la investigación posterior.\nCambia Contraseñas y Actualiza Software: Cambia todas las contraseñas afectadas por el ataque. Además, asegúrate de tener instaladas las últimas actualizaciones de seguridad en tus sistemas y software. Los ciberdelincuentes a menudo aprovechan vulnerabilidades conocidas para llevar a cabo ataques.\nRealiza Análisis de Seguridad: Después de mitigar el ataque inicial, realiza un análisis de seguridad en tu sistema para identificar cualquier punto débil o brecha de seguridad. Este análisis puede ayudar a fortalecer la seguridad de tu red y prevenir futuros ataques.',
        'ROBO DE IDENTIDAD PERSONAL': 'Contacta a las Autoridades: Informa a las autoridades locales, como la policía, sobre el robo de identidad. Presenta una denuncia formal para documentar el incidente.\nInforma a las Instituciones Financieras: Comunica a tus bancos, tarjetas de crédito y otras instituciones financieras sobre el robo. Cancela o congela cualquier cuenta afectada y establece medidas de seguridad adicionales, como contraseñas más fuertes o autenticación de dos factores.\nRevisa tus Estados de Cuenta: Examina detenidamente tus estados de cuenta bancarios y de tarjetas de crédito para detectar transacciones no autorizadas. Reporta cualquier actividad sospechosa a tu entidad financiera de inmediato.\nContacta a las Agencias de Crédito: Comunica a las agencias de informes crediticios, como Equifax, Experian y TransUnion, sobre el robo de identidad. Pide un informe de crédito gratuito y revisa cualquier actividad inusual. Considera poner un congelamiento de crédito para evitar que los delincuentes abran nuevas cuentas a tu nombre.\n Actualiza Contraseñas y Refuerza la Seguridad en Línea: Cambia todas tus contraseñas, especialmente aquellas relacionadas con información financiera y personal. Refuerza la seguridad en línea utilizando autenticación de dos factores siempre que sea posible.\nMantente Alerta y Educa: Está atento a posibles señales de actividad fraudulenta en el futuro. Educa a ti mismo y a tus seres queridos sobre las prácticas de seguridad en línea y las tácticas comunes de robo de identidad para evitar futuros incidentes.',
        'CONTRASEÑAS': 'Cambia tus Contraseñas: Cambia inmediatamente la contraseña de la cuenta afectada. Utiliza una contraseña fuerte y única que no hayas utilizado en otras cuentas. Si es posible, habilita la autenticación de dos factores para una capa adicional de seguridad.\nRevise la Configuración de Seguridad: Verifica y actualiza la configuración de seguridad de tu cuenta. Asegúrate de que la información de recuperación de cuenta, como direcciones de correo electrónico y números de teléfono, sea correcta y esté actualizada.\nRevise Actividades Recientes: Revisa la actividad reciente en tu cuenta para identificar cualquier actividad sospechosa. Muchos servicios en línea ofrecen historiales de actividad que te permiten ver cuándo y desde dónde se ha accedido a tu cuenta.\nNotifica al Servicio: Informa a la plataforma o servicio afectado sobre la pérdida de contraseña o el posible hackeo. Muchas plataformas tienen procedimientos específicos para recuperar cuentas comprometidas.\nEscanea tu Dispositivo en Busca de Malware: Realiza un escaneo completo de tu dispositivo con un programa antivirus confiable para buscar posibles malware o programas maliciosos que podrían haber comprometido tu seguridad.\nMonitoriza Otras Cuentas: Si utilizas la misma contraseña en otras cuentas, cámbiala de inmediato. Es una buena práctica utilizar contraseñas únicas para cada cuenta para evitar que un compromiso en una cuenta afecte a otras.',
        'ESTAFAS EN LINEA': 'Detén cualquier interacción adicional: Si sospechas que estás siendo estafado, deja de comunicarte de inmediato con la persona o entidad involucrada. No proporciones más información personal o financiera.\nGuarda evidencia: Toma capturas de pantalla de todas las comunicaciones y transacciones relacionadas con la estafa. Estas capturas pueden ser útiles al informar el incidente a las autoridades o a la plataforma de servicio.\nReporta a la plataforma o servicio: Informa sobre la estafa a la plataforma o servicio en el que ocurrió. Muchas plataformas en línea tienen procedimientos específicos para manejar estafas y actividades fraudulentas.\nContacta a tu institución financiera: Si la estafa involucra transacciones financieras, comunícate con tu banco o tarjeta de crédito de inmediato. Notifica sobre la situación y sigue sus instrucciones para disputar cargos no autorizados.\nCambia contraseñas: Cambia todas las contraseñas relacionadas con la estafa, especialmente si involucra cuentas en línea. Asegúrate de usar contraseñas fuertes y únicas.\nReporta a las autoridades: Si la estafa es grave y ha resultado en pérdidas significativas, presenta una denuncia ante las autoridades locales. Proporciona toda la evidencia recopilada y sigue cualquier proceso legal necesario.',
        'PHISHING': 'Cambia tu Contraseña: Si proporcionaste tu contraseña durante el ataque de phishing, cambia la contraseña de la cuenta afectada de inmediato. Utiliza una contraseña fuerte y única.\nHabilita la Autenticación de Dos Factores (2FA): Activa la autenticación de dos factores siempre que sea posible. Esto proporciona una capa adicional de seguridad al requerir un segundo método de verificación, como un código enviado a tu teléfono, además de la contraseña.\nInforma a la Plataforma o Servicio: Notifica a la plataforma o servicio afectado sobre el intento de phishing. Muchas plataformas tienen procedimientos para manejar incidentes de seguridad y pueden proporcionar asistencia.\nRevisa Actividades Recientes: Examina la actividad reciente en tus cuentas para detectar cualquier actividad no autorizada. Si encuentras algo sospechoso, repórtalo de inmediato a la plataforma correspondiente.\nEscanea tu Dispositivo en Busca de Malware: Realiza un escaneo completo de tu dispositivo con un programa antivirus actualizado. El phishing a veces va de la mano con malware que podría comprometer aún más la seguridad de tu sistema.\nSé Cauteloso con Correos Electrónicos y Enlaces: Aprende a identificar correos electrónicos y enlaces sospechosos. Verifica siempre la autenticidad de los mensajes antes de hacer clic en enlaces o proporcionar información personal. No hagas clic en enlaces en correos electrónicos que parezcan inusuales o soliciten información confidencial.',
        'ACTUALIZACIONES DE SOFTWARE': 'Parches de Seguridad: Las actualizaciones suelen incluir parches de seguridad que abordan vulnerabilidades recién descubiertas. Al mantener tu software actualizado, reduces el riesgo de ataques cibernéticos que podrían aprovechar esas vulnerabilidades.\nProtección contra Malware: Los desarrolladores de software lanzan actualizaciones para abordar nuevas amenazas de malware. Mantener actualizado tu sistema operativo y tus programas antivirus ayuda a protegerte contra las últimas amenazas en línea.\nMejora del Rendimiento: Las actualizaciones también pueden mejorar el rendimiento de tus aplicaciones y sistemas operativos. Los desarrolladores realizan mejoras y optimizaciones que pueden hacer que tus programas funcionen más suavemente y sean más eficientes.\nCompatibilidad con Nuevos Dispositivos o Tecnologías: A medida que la tecnología avanza, las actualizaciones aseguran que tu software sea compatible con nuevos dispositivos y tecnologías emergentes. Esto es crucial para garantizar que puedas aprovechar las últimas funciones y hardware.\nCorrección de Errores: Las actualizaciones también abordan errores y problemas conocidos en versiones anteriores del software. Corregir estos errores contribuye a una experiencia de usuario más estable y sin problemas.\nCumplimiento Normativo: En el caso de empresas y organizaciones, mantener el software actualizado es crucial para cumplir con regulaciones y normativas de seguridad. La falta de actualizaciones podría resultar en vulnerabilidades de seguridad y posibles sanciones.\nNuevas Funciones y Características: Además de correcciones y mejoras de seguridad, las actualizaciones a menudo introducen nuevas funciones y características que pueden mejorar la experiencia del usuario y brindar mayores posibilidades.'
    }

    return (
        <View style={styles.container}>
            <View style={styles.containerHorizontal}>
                <Image style={styles.logoHorizontal} source={require('../assets/img/netShield.png')}/>
                <Text style={styles.titleHorizontal}>Net Shield</Text>
            </View>

            <ScrollView style={styles.scrollContainer}>
                <View style={styles.stepsContainer}>
                    <Text style={styles.stepText}>{name}</Text>
                    <Text style={styles.stepText}>{text[name]}</Text>
                </View>
            </ScrollView>

        </View>
    )
}

export default CautionScreen;