import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#5D92B0',
    alignItems: 'center',
    padding: 16,
  },
  title: {
    marginTop: 16,
    fontWeight: '900',
    fontSize: 32,
    color: '#f4f5f6',
  },
  videocard: {
    marginTop: 16,
    borderRadius: 20,
    padding: 10,
    backgroundColor: '#f4f5f6',
    width: '100%',
    aspectRatio:'16/9',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  recommended: {
    borderRadius: 10,
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  separation: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    padding: 8,
  },
  videoicon: {
    width: 54,
    height: 54,
  },
  videoiconcont: {
    width: 'auto',
    height: 'auto',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#dddddd',
    borderRadius: 5,
    padding: 3,
  },
  scrollY: {
    marginTop: 16,
    borderRadius: 20,
    height: 'auto',
    backgroundColor: '#f4f5f6',
    width: '100%',
  },
  section: {
    marginTop: 16,
    paddingHorizontal: 16,
    display: 'flex',
    flexDirection: 'column',
  },
  course: {
    fontWeight: '700',
    fontSize: 24,
    color: '#1d2d3d',
  },
  scrollX: {
    paddingVertical: 16,
    width: '100%',
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    height: 'auto',
    width: 100,
  },
  imgcontainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: '#dddddd',
    width: 80,
    height: 80,
  },
  courseimage: {
    width: '90%',
    height: '90%',
  },
  name: {
    fontWeight: '600',
    fontSize: 12,
    color: '#1d2d3d',
    textAlign: 'center',
  },
  videotitle: {
    marginTop: 2,
    fontWeight: '600',
    fontSize: 24,
    color: '#f4f5f6',
    textAlign: 'center',
  },
  videosubtitlecont: {
    width: 'auto',
    height: 'auto',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#5D92B0',
    borderRadius: 5,
    paddingVertical: 3,
    paddingHorizontal: 8,
  },
  videosubtitle: {
    fontWeight: '900',
    fontSize: 16,
    color: '#f4f5f6',
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  badge: {
    width: 25,
    height: 25,
    position: 'absolute',
    zIndex: 1,
    right: 4,
    bottom: 4,
  },
  statusDone: {
    position: 'absolute',
    textAlign: 'center',
    zIndex: 1,
    bottom: 0,
    borderRadius: 10,
    backgroundColor: '#0cd39180',
    width: '100%',
    fontWeight: '600',
    color: '#f4f5f6',
  },
  statusIncomplete: {
    position: 'absolute',
    textAlign: 'center',
    zIndex: 1,
    bottom: 0,
    borderRadius: 10,
    backgroundColor: '#4a5a5d80',
    width: '100%',
    fontWeight: '600',
    color: '#f4f5f6',
  },
});